theme: "kube"
baseURL: https://datatodev.netlify.app/
languageCode: en-us
title: Data To Dev Collective

Params:
  logo: /BigLogo.svg
  logoHeight: 36px

menu:
  main:
    - name: Blog
      weight: -100
      url: /post/
