theme: "kube"
baseURL: https://datatodev.netlify.app/
languageCode: en-us
title: "Data to Dev Collective"
summaryLength: 20
paginate: 1

# markup:
#   defaultMarkdownHandler: blackfriday
# markup:
#   goldmark:
#     renderer:
#       unsafe: true

Params:
  logo: /images/BigLogo.svg
  logoHeight: 36px
  description: "Description text"

menu:
  main:
    - name: Projects
      url: /projects/
      weight: 1
    - name: Blog
      weight: 2
      url: /post/
    - name: Hire Us
      url: /contact-us.html/
      weight: 3
    - name: About
      url: ""
      identifier: About
      weight: 4
      post: <i class="fa fa-caret-down"></i>
    - name: About Us
      url: /about-us/
      parent: About
      weight: 1
    - name: What We Do
      url: /what-we-do/
      parent: About
      weight: 2
    - name: Team
      url: /team/
      parent: About
      weight: 3
    - name: Guidelines
      url: /guidelines.html/
      parent: About
      weight: 4
    - name: Join Us
      url: /join-us.html/
      parent: About
      weight: 5
  extra:
    - name: Linkedin
      url: https://www.linkedin.com/
      weight: 1
      pre: <i class="fa fa-linkedin fa-lg"></i>
    - name: Github
      url: https://www.github.com/DatatoDevCollective
      weight: 2
      pre: <i class="fa fa-github fa-lg"></i>
    - name: Twitter
      url: https://www.twitter.com/
      weight: 3
      pre: <i class="fa fa-twitter fa-lg"></i>
    - name: Contribute
      url: /contribute.html/
      weight: 4
  team:
    - name: Kiranmayi Vadlamudi
      params:
        designation: Co-Founder
        description: "Test description: Kiranmayi is a geospatial data scientist and a complexity science researcher."
        image: "/images/Kiran.jpg"
    - name: Manan Gupta
      params:
        designation: Co-Founder
        description: "Test description: Manan is a geospatial data scientist and an evolutionary biologist."
        image: "/images/Manan.jpg"